version: '3.8'

services:
  bot:
    build: .
    container_name: guardia-bot
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - MONGO_URI=${MONGO_URI}
    volumes:
      - .:/usr/src/bot
    restart: unless-stopped
